### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hosford42** [barrust/mediawiki#136]
Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
OS: Windows 11

Exception:

```python3
(.venv) PS C:\Users\Aaron Hosford>pip install mediawiki              
Collecting mediawiki
  Downloading mediawiki-0.0.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>  
          main()
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main      
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\PycharmProjects\ExplainableClassifiers\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel       
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-build-env-2jggal1j\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "C:\Users\Aaron Hosford\AppData\Local\Temp\pip-install-uwrmlzlj\mediawiki_688478c77c904bec86f108622d6afeb4\mediawiki\__init__.py", line 21, in <module>
          from wiki import *
      ModuleNotFoundError: No module named 'wiki'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by hosford42** [comment]
I tried running `pip install wiki` separately. `wiki` installed successfully, and I confirmed I could import it, but `pip install mediawiki` still bombed out with the exact same error... which is strange.

**Comment by barrust** [comment]
So those two projects are not part of `pymediawiki`. It looks like you are trying to install this project: [mediawiki](https://github.com/zikzakmedia/python-mediawiki/tree/master) which hasn't been updated since 2012. This project is not related to that tool. To install `pymediawiki` you simply need to run 
``` bash
pip install pymediawiki
```

**Comment by hosford42** [comment]
Ah, okay. Wow, that's an unfortunate wire-crossing for the names! Your repo on GitHub is named mediawiki, but installs with the name pymediawiki, while their repo is named python-mediawiki and installs with the name mediawiki.

In any case, the install for your package worked without issue. I suppose it's good to have this publicly documented for other folks who might be confused. Thanks for your help!
