### ISSUE TITLE
generate_test_data raises MediaWikiException for PULL_GEOSEARCH

### ISSUE THREAD

**Issue by shnela** [barrust/mediawiki#69]
If variable `PULL_GEOSEARCH` in script `generate_test_data.py` is set to True script ends with the following error:

> Traceback (most recent call last):
>   File "[removed content]/mediawiki/scripts/generate_test_data.py", line 217, in <module>
>     longitude=Decimal('0.0'), results=22, radius=10000)
>   File "../mediawiki/mediawiki/utilities.py", line 66, in wrapper
>     cache[func.__name__][key] = (time.time(), func(*args, **kwargs))
>   File "../mediawiki/mediawiki/mediawiki.py", line 489, in geosearch
>     self._check_error_response(raw_results, title)
>   File "../mediawiki/mediawiki/mediawiki.py", line 878, in _check_error_response
>     raise MediaWikiException(err)
> mediawiki.exceptions.MediaWikiException: An unknown error occured: "Page coordinates unknown.". Please report it on GitHub!

**Comment by shnela** [comment]
It may be connected with "New York" disambiguation, because while request for [New York](https://en.wikipedia.org/w/api.php?gspage=New%20York&action=query&list=geosearch) raises exceptions, request for [New York City](https://en.wikipedia.org/w/api.php?gspage=New%20York%20City&action=query&list=geosearch) works well.
